### ISSUE TITLE
Cannot set camera background effect

### ISSUE THREAD

**Issue by DeividasJanusas** [VidyoAPI-SDK/Swift-Sample#1]
VCConnector function `setCameraBackgroundEffect(_ effectInfo: VCConnectorCameraEffectInfo!) -> [Bool]` prints error 

> ERR: VidyoCameraEffect: Fail to start VidyoCameraEffect [ [System thread], 4487955840, VidyoCameraEffectStart, VidyoCameraEffect.c:782 ]

Either its effect type is set `.blur` or `.virtualBackground` outcome is the same.

Steps to reproduce:

1. Clone and prepare everything according to https://github.com/VidyoAPI-SDK/Swift-Sample
2. Build and run in debug mode
3. Press background button
4. Choose any background
5. No background is applied and debug console prints error

Tested on iPhone 6s (iOS 15.3) and iPhone 13 mini (iOS 17.2.1)

**Comment by rmanglaenghouse** [comment]
@DeividasJanusas : Can you please fetch the latest commit and try once. 

Root Cause - Our background effects feature is licensed based and for testing we put trial licenses on github with relatively short expiry. License had expired due to which camera effects were not working.

Solution - We have updated new test license.

**Comment by DeividasJanusas** [comment]
Hi,

Thank you for the response. I was able to set camera background effect with updated token
